---
language: ruby
sudo: false
# Delete dependency locks for matrix builds.
before_install: rm Gemfile.lock || true
script: bundle exec rake test
rvm:
  - 2.1.0
  - 2.2.0
env:
  - PUPPET_VERSION="~> 3.8.0"
  - PUPPET_VERSION="~> 4.10.0"
matrix:
  allow_failures:
  - env: PUPPET_VERSION="~> 4.10.0"
