---
# Verify this with: http://lint.travis-ci.org/
language: ruby
before_install: rm Gemfile.lock
rvm:
  - 1.8.7
  - 1.9.3
script: bundle exec rake spec
env:
  matrix:
  - PUPPET_VERSION=2.7.23
  - PUPPET_VERSION=3.1.1
