HOSTS:
  ubuntu-14-04:x
   platform: ubuntu-14.04-x86_64
   hypervisor: vagrant
   box: puppetlabs/ubuntu-14.04-64-nocm
   box_url: https://vagrantcloud.com/puppetlabs/boxes.ubuntu-14.04-64-nocm
   ip: 172.16.5.5
